services:
  # DATABASE
  postgres:
    image: postgres:17-alpine
    container_name: Database-dev
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: development_db_password
      POSTGRES_DB: my_portofolio_mikail
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: Caching-Prod
    restart: unless-stopped
    command: redis-server --requirepass development_redis_password
    environment:
      REDIS_PASSWORD: development_redis_password
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # BACKEND
  backend:
    build:
      context: ./backend
      target: dev
    container_name: Backend-dev
    ports:
      - "8000:8000"
      - "4983:4983"
    volumes:
      - ./backend:/app
      - upload_folder:/app/uploads
    env_file: ./backend/.env.dev
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  # FRONTEND
  frontend:
    build:
      context: ./frontend
      target: dev
    container_name: Frontend-dev
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
    env_file: ./frontend/.env.dev

volumes:
  postgres_data:
  upload_folder:
  redis_data: