services:
  # DATABASE
  postgres:
    image: postgres:17-alpine
    container_name: Database-dev
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: development_db_password
      POSTGRES_DB: my_portofolio_mikail
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  # BACKEND
  backend:
    build:
      context: ./backend
      target: dev
    container_name: Backend-dev
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
      - /app/node_modules
      - upload_folder:/app/uploads
    env_file: ./backend/.env.dev

  # FRONTEND
  frontend:
    build:
      context: ./frontend
      target: dev
    container_name: Frontend-dev
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - backend

volumes:
  postgres_data:
  upload_folder:
